### ISSUE TITLE
How does the software interact with "modi"

### ISSUE THREAD

**Issue by TheAlpiner** [gmeks/myUplinkSmartConnect#1]
Hi, nice work. Just got a 200L Høiax Connected installed  and found your software. I tested it out in a container and it seems to have connected ok. I just wanted to know how it interacts with the different "MODI"s. I had a set point for 60 and it changed to 70. But I have not changed and done anything to the MODI setup. Does your software use MODIS in an intelligent way? Did not find anything in the documentation for this. Below is my log file 

[16:19:44 INF] Starting up service
[16:19:44 INF] Reading settings from configuration file
[16:19:46 ERR] Failed to get updated price information, from EU API. Checking nordpool
[16:19:48 INF] Found device with ID: ###########
[16:19:49 WRN] Water heater target temperature is incorrect ({setting.value}) for {mode.name} , changing to 70
[16:19:49 WRN] Water heater desired power level is incorrect for {mode.name} , changing from {setting.HelperDesiredHeatingPower} to M4 (70C, 700W)
[16:19:49 WRN] Water heater target temperature is incorrect ({setting.value}) for {mode.name} , changing to 70
[16:19:49 WRN] Water heater desired power level is incorrect for {mode.name} , changing from {setting.HelperDesiredHeatingPower} to M5 (70C, 1300W)
[16:19:51 INF] Changed schedule for #########
[16:19:51 ERR] Failed to connect to MTQQ server 

But so far this looks very promising. :-)

**Comment by gmeks** [comment]
Hey,

The way it uses modes it uses 3 seperate modes

M6)
target temp 70C, max watt 2000.

M5)
Target temp 50c, max watt 700

M4) Target temp 50, but no heating allowed.


The basic idea is to use the low prices, to heat up the water to 70c ( That means there is no random legionenal program needed).
And if needed M5 kicks inn, and keeps the water hoot.


Il expand more on it tomorrow, see if i cannot expand the docs.

**Comment by gmeks** [comment]
Heater should be in schedule mode i belive. Thats when it checks the remote API to see what to do, but please note that it does not check instant.

The current method it works in, is to use lower electricity price to build up as much energi as posible in the tank, and store it there during high cost periods.
For me it seems using 70c as target temprature is the best middle ground, that way it lasts for many hours but does not "leak out" right away. Like using 80c target does.

Setting up homeassistant is a great idea, then you get to see what its doing. And perhaps combining our experiences will see the different knobs we will need to to have adjustable ( Like change target temprature of modes).

It might also be posible to use a different kind of target mode, we instead say that we want X amount of hot water at XX and YY. Basicity just making sure that it uses the best spot in the night for getting enough water for the morning showers. Currently the application does not have any "usage" information so i cannot know how much hot water is needed at different times.

The prices are released at 13:00, the application spreads out when it does the reschedule at a unique pr user time after this but before 22:00. 

Yea my plan for vacation was to change the heater to vacation mode. And then 1-2 before we come back switch it to schedule.  If we ever get to the point with full homeassisatnt integration it would be posible to many of these things from homeassistant.

**Comment by gmeks** [comment]
Im a bit confused, your using appconfig when running via docker?
In docker you should be using envromental variables ( I would recommend at least).,

Based on your setup, the target time is 13:17.

You should be seeing log lines like
[16:00:09 INF] Found device with ID: HOIAX_X
[16:00:11 INF] Changed schedule for HOIAX_X

Can you verify the  CheckRemoteStatsIntervalInMinutes 1 setting?
There is a LogLevel setting ( or just write debug in console when its running) .

And regarding reschedule on restart, turns out there was a bug. Thats fixed, il build a new version tomorrow... For your setup it will run the schedule tomorow. It will not force on reboot

**Comment by TheAlpiner** [comment]
It changed the schedule a little later so that part works greast just had to wait :-)

[16:00:39 ERR] Failed to get updated price information, from EU API. Checking nordpool
[16:00:46 INF] Found device with ID: HOIAX_###
[16:00:48 INF] Changed schedule for HOIAX_####

Did not get any further with MQTT integration though

> Im a bit confused, your using appconfig when running via docker? In docker you should be using envromental variables ( I would recommend at least).,

Yes probably should, it was a quick fix just to test.  :-)

> 
> There is a LogLevel setting ( or just write debug in console when its running) .
> 
> And regarding reschedule on restart, turns out there was a bug. Thats fixed, il build a new version tomorrow... For your setup it will run the schedule tomorow. It will not force on reboot

OK, great

> 
> Can you verify the CheckRemoteStatsIntervalInMinutes 1 setting? MQTT messages should be sendt 1 time pr minute, and its multiple messages pr minute

That setting is there. I can do som more research on the MQTT problem. I have not dived very deep into it. The strange thing is it seems to connect but no messages is coming. The schedule seems to work great but it fire an error eaxch time on EU API it seems. Or maybe it says nothing when it goes ok :-)

**Comment by gmeks** [comment]
It should do a fallback to another API if EU is down. But its easy to check in the myapi website to verify that it updated the schedule.

in regards to MQTT im running the one that comes as a homeassistant addon. Running via docker compose like this.

```
version: "2"

services:
  server:
    image: erlingsaeterdal/myuplinksmartconnect:latest
    restart: always
    pull_policy: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - TZ=Europe/Oslo     
      - UserName=eks@something
      - Password=anothersupersercretpassword
      - IsInsideDocker=1
      - CheckRemoteStatsIntervalInMinutes=1      
      - WaterHeaterMaxPowerInHours=5
      - WaterHeaterMediumPowerInHours=12
      - PowerZone=NO2
      - MQTTServer=192.168.50.10
      - MQTTServerPort=1883
      - MQTTUserName=homeassistant
      - MQTTPassword=supersecretpassword
```

**Comment by gmeks** [comment]
I pushed tag erlingsaeterdal/myuplinksmartconnect:1.0.0.5 added more logging for you, and fixed the schedule not starting on app restart.

**Comment by gmeks** [comment]
Btw appconfig seems to not support strings, so setting  LogLevel to 1 to set debug.

**Comment by TheAlpiner** [comment]
> I pushed tag erlingsaeterdal/myuplinksmartconnect:1.0.0.5 added more logging for you, and fixed the schedule not starting on app restart.

Great thanks, i will test the new version and also see if the extended logging will help. 🙂👍

**Comment by gmeks** [comment]
Its in erlingsaeterdal/myuplinksmartconnect:latest now, i have experienced a flaw that can make it stop doing updates. Seems to be related to homeassistant reboots. But not sure yet

**Comment by gmeks** [comment]
I think i found the bug, that could make stop doing updates. It was as expected very stupid, patch is in latest

**Comment by TheAlpiner** [comment]
Hi, I have updated to the latest version and can now verify with MQTT explorer that it is sending messages to the broker.

[11:29:57 INF] Target Schedule change time is 17:17
[11:29:57 INF] Starting up service
[11:29:57 INF] Reading settings from environmental variables
[11:29:57 INF] Reporting to MQTT is: True
[11:30:58 INF] Found device with ID: HOIAX_###

But for some reason it is not creating them in HomeAssistant. I think that is due to my lack of knowledge regarding HA. I have verified with the MQTT Explorer that the topic header is correct but it still not creating the sensors. But i will dig into this. Thank you for your continuing work on this. The updates to myuplink worked flawlessly in the last version. I will check after 17:17 today :-)

**Comment by gmeks** [comment]
It will not create then, you have to add it to configuration.yml  like the example:

```
 sensor:
   - platform: mqtt
     state_topic: "heater/18760NE2240322014631/TargetTemprature"
     unique_id: "WaterHeaterTargetTemprature"
     name: "Target temprature"
     unit_of_measurement: "°C"
     
   - platform: mqtt
     state_topic: "heater/18760NE2240322014631/CurrentTemprature"
     unique_id: "WaterHeaterCurrentTemprature"
     name: "Current temprature"
     unit_of_measurement: "°C"
     
   - platform: mqtt
     state_topic: "heater/18760NE2240322014631/EstimatedPower"
     unique_id: "WaterHeaterEstimatedPower"    
     name: "Current Watt"
     device_class: power    
     state_class: measurement    
     unit_of_measurement : W   
    
  - platform: mqtt
    state_topic: "heater/18760NE2240322014631/EnergyTotal"
    unique_id: "WaterHeaterEnergyTotal"
    name: "Energy Total"    
    device_class: power
    state_class: total_increasing
    unit_of_measurement : kWh    
    
  - platform: mqtt
    state_topic: "heater/18760NE2240322014631/EnergiStored"
    unique_id: "WaterHeaterEnergiStored"
    name: "Energi in tank"
    device_class: power
    unit_of_measurement : kWh        
    
  - platform: mqtt
    state_topic: "heater/18760NE2240322014631/FillLevel"
    name: "Tank fill level"
    unique_id: "WaterHeaterFillLevel"    
    unit_of_measurement: '%'

  - platform: mqtt
    state_topic: "heater/18760NE2240322014631/LastScheduleChangeInHours"
    name: "Last schedule change"
    unique_id: "LastScheduleChange" 
```
